"""post-receive entrypoint: generate cache artifacts for each pushed branch.

Wire it up with a thin shell shim (see hooks/post-receive) that execs
``python -m agentcache.hook``. Stdin gets one line per updated ref:

    <old-oid> <new-oid> <refname>

We generate for branch tips (refs/heads/*), skip deletions, and emit a
blobless bootstrap bundle if AGENTCACHE_BUNDLE_DIR is set.
"""
from __future__ import annotations

import json
import os
import sys
from typing import Any, Dict

import pygit2

from . import GENERATOR_VERSION
from .config import AgentCacheConfig
from . import bundle as bundle_mod
from . import cache_writer
from . import manifest as manifest_mod
from . import symbols as symbols_mod

ZERO_OID = "0" * 40


def _render_agents_md(cfg: AgentCacheConfig, meta: Dict[str, Any], commit_oid: str) -> bytes:
    """Render a complete, actionable agents.md document for this cache commit.

    Uses values already present in *meta* so no additional I/O is required.
    """
    service_url = cfg.service_url if cfg.service_url else "<AGENTCACHE_SERVICE_URL>"
    generated_at = meta.get("generated_at", "")
    entry_count = meta.get("manifest_entries", 0)
    symbol_count = meta.get("symbol_count", 0)
    ctags_available = meta.get("ctags_available", False)

    doc = f"""\
# Agent Instructions — agentcache cold-start

<!-- generated by agentcache v{GENERATOR_VERSION} -->
<!-- commit: {commit_oid} | generated_at: {generated_at} -->
<!-- manifest_entries: {entry_count} | symbol_count: {symbol_count} | ctags_available: {ctags_available} -->

> This document is stored as a cache artifact alongside `manifest.json`,
> `symbols.json`, and `meta.json` in the orphaned cache commit for
> `{commit_oid}`.  It is served at `{service_url}/cache/{commit_oid}/agents.md`
> and at `{service_url}/agents.md` (most-recent cache alias).

---

## Cold-start protocol

This repository's git server runs agentcache.  Instead of a full or
shallow clone, use this three-step sequence.  You only fetch the blobs
you are going to read.

```bash
# ── 0.  Pin the commit ────────────────────────────────────────────────
COMMIT={commit_oid}

# ── 1.  Blobless clone — commits + trees, zero content bytes ──────────
git clone \\
  --filter=blob:none \\
  --no-checkout \\
  <REPO_URL> workspace
cd workspace

# ── 2.  Resolve — ask which OIDs you need, no content transferred ─────
OIDS=$(curl -s -XPOST "{service_url}/cache/${{COMMIT}}/resolve" \\
       -H 'content-type: application/json' \\
       -d '{{"paths":["src/app.py","src/util.c"]}}' \\
     | jq -r '.fetch_oids[]')

# ── 3.  Fetch — ONE batched packfile, only what you need ──────────────
git fetch origin $OIDS

# Read blobs by OID (no working-tree checkout required):
git cat-file blob <OID>
```

---

## Service endpoints

Base URL: `{service_url}`

| Method | Path | Purpose |
|--------|------|---------|
| `GET`  | `/healthz` | Liveness check — `{{"status":"ok"}}` |
| `GET`  | `/caches` | List commits that have a cache entry |
| `GET`  | `/cache/<commit>/manifest` | Full flat path→{{oid,size,mode}} for the commit |
| `GET`  | `/cache/<commit>/agents.md` | This document, rendered for a specific commit |
| `GET`  | `/agents.md` | This document for the most-recently cached commit |
| `GET`  | `/cache/<commit>/symbol/<name>` | All locations of a symbol + their OIDs |
| `POST` | `/cache/<commit>/resolve` | Resolve a list of paths → `{{fetch_oids, missing, total_bytes}}` |

---

## Symbol lookup

```bash
# Where is TokenRefresher defined, and what blob OID do I fetch?
curl -s "{service_url}/cache/{commit_oid}/symbol/TokenRefresher" | jq .
# → {{"name":"TokenRefresher","locations":[{{"path":"src/app.py","line":5,"kind":"class","oid":"abc123...","size":1234}}],"fetch_oids":["abc123..."]}}

# Fetch that blob directly:
git fetch origin abc123...
git cat-file blob abc123...
```

This turns "grep the entire repo" (fetch all blobs, scan) into a lookup
that returns a handful of OIDs, fetched in one pack.

---

## Cache metadata for this commit

| Field | Value |
|-------|-------|
| `source_commit` | `{commit_oid}` |
| `generated_at` | `{generated_at}` |
| `manifest_entries` | {entry_count} |
| `symbol_count` | {symbol_count} |
| `ctags_available` | {ctags_available} |
| `generator_version` | {GENERATOR_VERSION} |

---

*Generated by [agentcache](https://github.com/cdibona/AgentCache) v{GENERATOR_VERSION}.*
"""
    return doc.encode()


def generate_for_commit(
    repo: pygit2.Repository, commit_oid: str, cfg: AgentCacheConfig
) -> Dict[str, Any]:
    """Build artifacts for one commit, store under the side ref, return summary."""
    man = manifest_mod.build_manifest(repo, commit_oid)
    syms = symbols_mod.build_symbol_index(repo, commit_oid, ctags_bin=cfg.ctags_bin)
    meta = {
        "schema": 1,
        "generator_version": GENERATOR_VERSION,
        "source_commit": str(commit_oid),
        "generated_at": man["generated_at"],
        "manifest_entries": man["entry_count"],
        "symbol_count": syms["symbol_count"],
        "ctags_available": syms["ctags_available"],
    }
    artifacts = {
        "manifest.json": json.dumps(man, separators=(",", ":")).encode(),
        "symbols.json": json.dumps(syms, separators=(",", ":")).encode(),
        "meta.json": json.dumps(meta, indent=2).encode(),
        "agents.md": _render_agents_md(cfg, meta, str(commit_oid)),
    }
    result = cache_writer.write_cache(
        repo,
        commit_oid,
        artifacts,
        ref_prefix=cfg.ref_prefix,
        bot_name=cfg.bot_name,
        bot_email=cfg.bot_email,
    )
    result["meta"] = meta
    return result


def _handle_ref(repo, old_oid, new_oid, refname, cfg) -> Dict[str, Any] | None:
    if new_oid == ZERO_OID:
        return None  # branch deletion
    if not refname.startswith("refs/heads/"):
        return None  # only branch tips
    summary = generate_for_commit(repo, new_oid, cfg)
    summary["ref"] = refname
    if cfg.bundle_dir:
        out = os.path.join(cfg.bundle_dir, f"{new_oid}.bundle")
        bundle_mod.create_blobless_bundle(
            repo, refname, out, filter_spec=cfg.bundle_filter
        )
        summary["bundle"] = out
    return summary


def main(argv=None, stdin=None) -> int:
    stdin = stdin if stdin is not None else sys.stdin
    cfg = AgentCacheConfig.from_env()
    repo = pygit2.Repository(cfg.repo_dir)

    any_done = False
    for line in stdin:
        parts = line.split()
        if len(parts) != 3:
            continue
        old_oid, new_oid, refname = parts
        try:
            summary = _handle_ref(repo, old_oid, new_oid, refname, cfg)
        except Exception as exc:  # never block the push on cache failure
            print(f"agentcache: FAILED for {refname}: {exc}", file=sys.stderr)
            continue
        if summary:
            any_done = True
            print(
                "agentcache: {ref} -> {cache_ref} "
                "({n} files, {s} symbols, ctags={c})".format(
                    ref=summary["ref"],
                    cache_ref=summary["cache_ref"],
                    n=summary["meta"]["manifest_entries"],
                    s=summary["meta"]["symbol_count"],
                    c=summary["meta"]["ctags_available"],
                ),
                file=sys.stderr,
            )
    if not any_done:
        print("agentcache: nothing to do", file=sys.stderr)
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
