"""post-receive entrypoint: generate cache artifacts for each pushed branch.

Wire it up with a thin shell shim (see hooks/post-receive) that execs
``python -m agentgitsmart.hook``. Stdin gets one line per updated ref:

    <old-oid> <new-oid> <refname>

We generate for branch tips (refs/heads/*), skip deletions, and emit a
blobless bootstrap bundle if AGENTGITSMART_BUNDLE_DIR is set.
"""

from __future__ import annotations

import json
import os
import sys
from dataclasses import dataclass
from typing import Any, Dict, Optional

import pygit2

from . import GENERATOR_VERSION
from .config import AgentGitSmartConfig
from . import bundle as bundle_mod
from . import cache_writer
from . import manifest as manifest_mod
from . import symbols as symbols_mod

ZERO_OID = "0" * 40


def _render_agents_md(
    cfg: AgentGitSmartConfig, meta: Dict[str, Any], commit_oid: str
) -> bytes:
    """Render a complete, actionable agents.md document for this cache commit.

    Uses values already present in *meta* so no additional I/O is required.
    """
    service_url = cfg.service_url if cfg.service_url else "<AGENTGITSMART_SERVICE_URL>"
    generated_at = meta.get("generated_at", "")
    entry_count = meta.get("manifest_entries", 0)
    symbol_count = meta.get("symbol_count", 0)
    ctags_available = meta.get("ctags_available", False)

    doc = f"""\
# Agent Instructions — agentgitsmart cold-start

<!-- generated by agentgitsmart v{GENERATOR_VERSION} -->
<!-- commit: {commit_oid} | generated_at: {generated_at} -->
<!-- manifest_entries: {entry_count} | symbol_count: {symbol_count} | ctags_available: {ctags_available} -->

> This document is stored as a cache artifact alongside `manifest.json`,
> `symbols.json`, and `meta.json` in the orphaned cache commit for
> `{commit_oid}`.  It is served at `{service_url}/cache/{commit_oid}/agents.md`
> and at `{service_url}/agents.md` (most-recent cache alias).

---

## Cold-start protocol

This repository's git server runs agentgitsmart.  Instead of a full or
shallow clone, use this three-step sequence.  You only fetch the blobs
you are going to read.

```bash
# ── 0.  Pin the commit ────────────────────────────────────────────────
COMMIT={commit_oid}

# ── 1.  Blobless clone — commits + trees, zero content bytes ──────────
git clone \\
  --filter=blob:none \\
  --no-checkout \\
  <REPO_URL> workspace
cd workspace

# ── 2.  Resolve — ask which OIDs you need, no content transferred ─────
OIDS=$(curl -s -XPOST "{service_url}/cache/${{COMMIT}}/resolve" \\
       -H 'content-type: application/json' \\
       -d '{{"paths":["src/app.py","src/util.c"]}}' \\
     | jq -r '.fetch_oids[]')

# ── 3.  Fetch — ONE batched packfile, only what you need ──────────────
git fetch origin $OIDS

# Read blobs by OID (no working-tree checkout required):
git cat-file blob <OID>
```

---

## Service endpoints

Base URL: `{service_url}`

| Method | Path | Purpose |
|--------|------|---------| 
| `GET`  | `/healthz` | Liveness check — `{{"status":"ok"}}` |
| `GET`  | `/caches` | List commits that have a cache entry |
| `GET`  | `/cache/<commit>/manifest` | Full flat path→{{oid,size,mode}} for the commit |
| `GET`  | `/cache/<commit>/agents.md` | This document, rendered for a specific commit |
| `GET`  | `/agents.md` | This document for the most-recently cached commit |
| `GET`  | `/cache/<commit>/symbol/<name>` | All locations of a symbol + their OIDs |
| `POST` | `/cache/<commit>/resolve` | Resolve a list of paths → `{{fetch_oids, missing, total_bytes}}` |

---

## Symbol lookup

```bash
# Where is TokenRefresher defined, and what blob OID do I fetch?
curl -s "{service_url}/cache/{commit_oid}/symbol/TokenRefresher" | jq .
# → {{"name":"TokenRefresher","locations":[{{"path":"src/app.py","line":5,"kind":"class","oid":"abc123...","size":1234}}],"fetch_oids":["abc123..."]}}

# Fetch that blob directly:
git fetch origin abc123...
git cat-file blob abc123...
```

This turns "grep the entire repo" (fetch all blobs, scan) into a lookup
that returns a handful of OIDs, fetched in one pack.

---

## Cache metadata for this commit

| Field | Value |
|-------|-------|
| `source_commit` | `{commit_oid}` |
| `generated_at` | `{generated_at}` |
| `manifest_entries` | {entry_count} |
| `symbol_count` | {symbol_count} |
| `ctags_available` | {ctags_available} |
| `generator_version` | {GENERATOR_VERSION} |

---

*Generated by [agentgitsmart](https://github.com/cdibona/AgentGitSmart) v{GENERATOR_VERSION}.*
"""
    return doc.encode()


# ---------------------------------------------------------------------------
# Delta strategy decision.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class _SymStrategy:
    """Result of the delta-vs-full strategy decision.

    Attributes:
        mode:           ``"full"`` or ``"delta"``.
        parent:         Parent commit OID for delta mode, else ``None``.
        reason:         Fallback reason string for non-root full builds,
                        else ``None``.
        parent_symbols: Parsed parent ``symbols.json`` dict for delta mode,
                        else ``None``.
    """

    mode: str
    parent: Optional[str]
    reason: Optional[str]
    parent_symbols: Optional[Dict[str, Any]]


def _decide_symbol_strategy(
    repo: pygit2.Repository,
    commit_oid: str,
    cfg: AgentGitSmartConfig,
) -> _SymStrategy:
    """FIRST-MATCH-WINS precedence ladder for delta vs full symbol indexing.

    Walks through eligibility conditions in order; the first condition that
    fails returns a full-build strategy with the corresponding reason string.
    Root commits and delta-eligible commits return a ``None`` reason.
    """
    _full = lambda reason: _SymStrategy(  # noqa: E731
        mode="full", parent=None, reason=reason, parent_symbols=None
    )

    # 1. Delta feature disabled.
    if not cfg.delta_symbols:
        return _full("delta_disabled")

    # 2. ctags unavailable right now.
    if not symbols_mod.ctags_available(cfg.ctags_bin):
        return _full("ctags_unavailable")

    # Read commit parents.
    commit = repo[commit_oid]
    if isinstance(commit, pygit2.Tag):
        commit = commit.peel(pygit2.Commit)
    parent_ids = list(commit.parent_ids)

    # 3. Root commit (no parents) — natural full build, no fallback reason.
    if not parent_ids:
        return _full(None)

    # Choose the first parent as the delta base.
    first_parent = str(parent_ids[0])

    # 4. Merge commit with delta_on_merge disabled.
    if len(parent_ids) > 1 and not cfg.delta_on_merge:
        return _full("merge_commit")

    # 5. Parent has no cache ref.
    parent_ref = f"{cfg.ref_prefix.rstrip('/')}/{first_parent}"
    if parent_ref not in repo.references:
        return _full("parent_uncached")

    # 6. Parent symbols.json unreadable.
    try:
        raw = cache_writer.read_artifact(
            repo, first_parent, "symbols.json", ref_prefix=cfg.ref_prefix
        )
        parent_syms = json.loads(raw)
    except (KeyError, json.JSONDecodeError):
        return _full("parent_unreadable")

    # 7. Schema or generator version mismatch.
    if parent_syms.get("schema") != symbols_mod.SYMBOLS_SCHEMA:
        return _full("schema_mismatch")
    if parent_syms.get("generator_version") != GENERATOR_VERSION:
        return _full("version_mismatch")

    # 8. Parent was built without ctags (can't carry forward reliable data).
    if not parent_syms.get("ctags_available", False):
        return _full("parent_ctags_unavailable")

    # All checks passed — delta eligible.
    return _SymStrategy(
        mode="delta",
        parent=first_parent,
        reason=None,
        parent_symbols=parent_syms,
    )


# ---------------------------------------------------------------------------
# Cache generation.
# ---------------------------------------------------------------------------


def generate_for_commit(
    repo: pygit2.Repository, commit_oid: str, cfg: AgentGitSmartConfig
) -> Dict[str, Any]:
    """Build artifacts for one commit, store under the side ref, return summary."""
    man = manifest_mod.build_manifest(repo, commit_oid)
    strategy = _decide_symbol_strategy(repo, commit_oid, cfg)

    files_in_tree = man["entry_count"]
    path_sizes = {e["path"]: e["size"] or 0 for e in man["entries"]}

    if strategy.mode == "delta":
        assert strategy.parent is not None  # guaranteed by _decide_symbol_strategy
        assert strategy.parent_symbols is not None

        diff = symbols_mod.diff_paths(repo, strategy.parent, commit_oid)

        # Re-check ratio threshold now that we have the actual diff.
        if (
            cfg.delta_max_ratio is not None
            and files_in_tree > 0
            and diff.changed_count / files_in_tree > cfg.delta_max_ratio
        ):
            # Downgrade to full build.
            syms = symbols_mod.build_symbol_index(
                repo, commit_oid, ctags_bin=cfg.ctags_bin
            )
            ctags_ok = syms["ctags_available"]
            generation: Dict[str, Any] = {
                "mode": "full",
                "parent": None,
                "files_in_tree": files_in_tree,
                "files_changed": files_in_tree,
                "files_reindexed": files_in_tree if ctags_ok else 0,
                "files_carried_forward": 0,
                "content_bytes_materialized": sum(path_sizes.values())
                if ctags_ok
                else 0,
                "symbol_count": syms["symbol_count"],
                "ctags_available": ctags_ok,
                "fallback_reason": "ratio_threshold",
            }
        else:
            syms = symbols_mod.build_symbol_index_delta(
                repo,
                commit_oid,
                strategy.parent_symbols,
                diff,
                ctags_bin=cfg.ctags_bin,
            )
            generation = {
                "mode": "delta",
                "parent": strategy.parent,
                "files_in_tree": files_in_tree,
                "files_changed": diff.changed_count,
                "files_reindexed": len(diff.reindex),
                "files_carried_forward": files_in_tree - len(diff.reindex),
                "content_bytes_materialized": sum(
                    path_sizes.get(p, 0) for p in diff.reindex
                ),
                "symbol_count": syms["symbol_count"],
                "ctags_available": syms["ctags_available"],
                "fallback_reason": None,
            }
    else:
        syms = symbols_mod.build_symbol_index(repo, commit_oid, ctags_bin=cfg.ctags_bin)
        ctags_ok = syms["ctags_available"]
        generation = {
            "mode": "full",
            "parent": None,
            "files_in_tree": files_in_tree,
            "files_changed": files_in_tree,
            "files_reindexed": files_in_tree if ctags_ok else 0,
            "files_carried_forward": 0,
            "content_bytes_materialized": sum(path_sizes.values()) if ctags_ok else 0,
            "symbol_count": syms["symbol_count"],
            "ctags_available": ctags_ok,
            "fallback_reason": strategy.reason,
        }

    meta = {
        "schema": 1,
        "generator_version": GENERATOR_VERSION,
        "source_commit": str(commit_oid),
        "generated_at": man["generated_at"],
        "manifest_entries": man["entry_count"],
        "symbol_count": syms["symbol_count"],
        "ctags_available": syms["ctags_available"],
        "generation": generation,
    }
    artifacts = {
        "manifest.json": json.dumps(man, separators=(",", ":")).encode(),
        "symbols.json": json.dumps(syms, separators=(",", ":")).encode(),
        "meta.json": json.dumps(meta, indent=2).encode(),
        "agents.md": _render_agents_md(cfg, meta, str(commit_oid)),
    }
    result = cache_writer.write_cache(
        repo,
        commit_oid,
        artifacts,
        ref_prefix=cfg.ref_prefix,
        bot_name=cfg.bot_name,
        bot_email=cfg.bot_email,
    )
    result["meta"] = meta
    result["generation"] = generation
    return result


def _handle_ref(repo, old_oid, new_oid, refname, cfg) -> Dict[str, Any] | None:
    # Loop prevention (defense in depth): never (re)generate a cache for our own
    # cache namespace. Writing refs/agent-git-smart/* is an in-process ref write that
    # cannot re-fire post-receive, and the refs/heads/* allowlist below already
    # excludes it — but make the guarantee explicit and config-correct so a custom
    # AGENTGITSMART_REF_PREFIX can't ever feed the hook its own artifacts.
    if refname.startswith(cfg.ref_prefix.rstrip("/") + "/"):
        return None
    if new_oid == ZERO_OID:
        return None  # branch deletion
    if not refname.startswith("refs/heads/"):
        return None  # only branch tips
    summary = generate_for_commit(repo, new_oid, cfg)
    summary["ref"] = refname
    if cfg.bundle_dir:
        out = os.path.join(cfg.bundle_dir, f"{new_oid}.bundle")
        bundle_mod.create_blobless_bundle(
            repo, refname, out, filter_spec=cfg.bundle_filter
        )
        summary["bundle"] = out
    return summary


# ---------------------------------------------------------------------------
# Loop-safety guarantee.
#
# AgentGitSmart cannot trigger itself in a feedback loop: cache artifacts are
# stored via repo.references.create() — an in-process libgit2 call that does
# NOT invoke receive-pack and therefore cannot re-fire post-receive. The hook
# only processes refs/heads/* (branch tips), so refs/agent-git-smart/* written by
# write_cache() are structurally excluded by the allowlist check below.
# Additionally, _handle_ref() explicitly guards against any ref whose name
# starts with cfg.ref_prefix, making the guarantee config-correct even when
# AGENTGITSMART_REF_PREFIX is customised. The GitHub Action mirrors this:
# the artifact push targets refs/agent-git-smart/<sha> (a non-branch ref) which
# can never match the ``push: branches: [main]`` workflow trigger.
# ---------------------------------------------------------------------------


def main(argv=None, stdin=None) -> int:
    stdin = stdin if stdin is not None else sys.stdin
    cfg = AgentGitSmartConfig.from_env()
    repo = pygit2.Repository(cfg.repo_dir)

    any_done = False
    for line in stdin:
        parts = line.split()
        if len(parts) != 3:
            continue
        old_oid, new_oid, refname = parts
        try:
            summary = _handle_ref(repo, old_oid, new_oid, refname, cfg)
        except Exception as exc:  # never block the push on cache failure
            print(f"agentgitsmart: FAILED for {refname}: {exc}", file=sys.stderr)
            continue
        if summary:
            any_done = True
            gen = summary.get("generation", {})
            print(
                "agentgitsmart: {ref} -> {cache_ref} "
                "({n} files, {s} symbols, ctags={c}, mode={m}, reindexed={r})".format(
                    ref=summary["ref"],
                    cache_ref=summary["cache_ref"],
                    n=summary["meta"]["manifest_entries"],
                    s=summary["meta"]["symbol_count"],
                    c=summary["meta"]["ctags_available"],
                    m=gen.get("mode", "full"),
                    r=gen.get("files_reindexed", 0),
                ),
                file=sys.stderr,
            )
    if not any_done:
        print("agentgitsmart: nothing to do", file=sys.stderr)
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
